### PR TITLE
Transitions and help with the ssh key

### PR DESCRIPTION
**Pull request by PaulProjects**
I changed two things:

1. The Intro and Chapter 5 had no transition to the next chapter.
2. I had to include the ssh key in order to connect without the ssh password, so I included it for others who face that issue.

Feel free to edit my additions.

### CODE REVIEW

**Comment by demhademha** [comment]
Could you please check the comment for **chapter 3**

**Comment by PaulProjects** [comment]
What do you mean with that?

**Comment by demhademha** [comment]
Ssh-keygen should automatically set this up. This is **unless** the user chose a different directory, which they are **explisitly** told not to.

**Comment by demhademha** [comment]
When setting up an ssh key, ssh usually notes the location of the key. If you user changes this location, they then have to specify the location of the key.

**Comment by PaulProjects** [comment]
Ok, somehow this didn't work for me. I gonna remove the changes to Chapter 3. Thank you for elaborating.

**Comment by demhademha** [comment]
Concerning your issue, feel free to join the discord server for support. 
I will now merge your pull request

**Pull request merged**
