### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0x14307**

### CODE REVIEW

**Comment by demhademha** [comment]
Hi, once you've fixed the issue with this pr, it will be merged. 
Thank you

**Comment by 0x14307** [comment]
There are no issues with this PR

**Comment by demhademha** [comment]
Please fix the **suggestion**

**Review by 0x14307 — COMMENTED** [review]
The only thing that is changed is that Chapter 6 is shown in the README, that is it.

**Comment by demhademha** [comment]
The link needs to display the actual heading from chapter 6, which is **Your first c program**

**Comment by 0x14307** [comment]
The link of the markdown file is the exact same link to the one in the pull request.

**Comment by demhademha** [comment]
Please change the line:
```
* [Chapter 6](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-6.md) Writing your first code
```
**to**:
```
* [Chapter 6](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-6.md) Writing your first c program
```
Thank you

**Comment by demhademha** [comment]
It just needs to say **writing your first c program**

**Comment by 0x14307** [comment]
It literally was changed to say that

**Comment by demhademha** [comment]
Your's says: **writing your c program** not **Writing your first c program**

**Comment by demhademha** [comment]
Your pull request has been merged. Have a great day.

**Pull request merged**
