### PR TITLE
Fix typos and clean up

### PR DESCRIPTION
**Pull request by raspberryenvoie**
Hi,
Thanks for making this guide!

### CODE REVIEW

**Comment by demhademha** [comment]
Thank you for the pull request I'll need to take a look when I get home before I accept it

**Comment by freyta** [comment]
Not sure if it is worth making a pull request, but you have an error that was missed:

Line 10 in chapter-1.md the word **wether** should be **whether**.

There are also quite a few double spaces instead of just single ones.

**Comment by demhademha** [comment]
Are we ready to merge this?

**Comment by raspberryenvoie** [comment]
Thank you @freyta I've missed that one!

@demhademha I'm done. If it's fine for you, you can merge it.

**Comment by demhademha** [comment]
Merged, have a great day :)

**Comment by raspberryenvoie** [comment]
Thank you so much, have an amazing day too!

**Pull request merged**
