### PR TITLE
added instruction for installing apk on iSH new versions

### PR DESCRIPTION
**Pull request by Silverethical**
iSH default rootfs no longer includes apk.

### CODE REVIEW

**Comment by demhademha** [comment]
The TestFlight version still has apk, I think you'll want to change the TestFlight link to the AppStore's and then I can merge
Thanks .

**Comment by Silverethical** [comment]
> The TestFlight version still has apk, I think you'll want to change the TestFlight link to the AppStore's and then I can merge
> Thanks .

I double-checked and the TestFlight version does not have apk either. (I uninstalled ish then reinstalled it from TestFlight and it did not have apk)
But I changed the link to AppStore nevertheless.

**Comment by demhademha** [comment]
Thank you, I will merge this now.

**Comment by demhademha** [comment]
Merged, have a great day :)

**Pull request merged**
